#!/usr/bin/env python

# Software License Agreement (BSD License)
#
# Copyright (c) 2012-2013, Eucalyptus Systems, Inc.
# All rights reserved.
#
# Redistribution and use of this software in source and binary forms, with or
# without modification, are permitted provided that the following conditions
# are met:
#
#   Redistributions of source code must retain the above
#   copyright notice, this list of conditions and the
#   following disclaimer.
#
#   Redistributions in binary form must reproduce the above
#   copyright notice, this list of conditions and the
#   following disclaimer in the documentation and/or other
#   materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Author: Matt Spaulding mspaulding@eucalyptus.com

import os
import sys

from argparse import ArgumentParser

from arado.api import APIWrapper, PathBuilder
from arado import repo
from arado import signing
from arado import __version__


if __name__ == "__main__":
    parser = ArgumentParser(description="""Rebuild an existing repository by
            resigning package and rebuilding metadata""")
    parser.add_argument("--project", dest="project",
        help="project for build promotion (e.g. eucalyptus)")
    parser.add_argument("--commit", dest="commit",
        help="reference to a commit; either a hash, tag, or branch")
    parser.add_argument("--release", dest="release",
        help="point-release version (e.g. 3.2)")
    parser.add_argument("--type", dest="buildtype", default="nightly",
        help="optionally supply a build type (release, prerelease, nightly)")
    parser.add_argument("--key", dest="signingkey",
        help="optionally supply a signing key (release, prerelease, nightly)")
    parser.add_argument("--gpgdir", dest="gpgdir",
        help="optionally supply gpg key directory")
    args = parser.parse_args()

    if None in (args.project, args.commit, args.release):
        parser.error("Must specify project, commit and release!")

    if args.gpgdir:
        signing.set_gpghome(args.gpgdir)

    api = APIWrapper(args.project, args.commit)
    builder = PathBuilder(api=api, buildtype=args.buildtype, release=args.release)

    temp_repo = repo.stage(builder.dest_path, True)
    repo.sign(temp_repo, args.signingkey)
    repo.rebuild_all(temp_repo)
    repo.replace(temp_repo, builder.dest_path)

